# Generated by Django 6.0.2 on 2026-02-13 15:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFocusDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('career_focus', models.CharField(choices=[('result', 'Результат'), ('development', 'Развитие'), ('enjoyment', 'Удовольствие')], max_length=20, verbose_name='Базовое направление')),
            ],
            options={
                'verbose_name': 'Направление в работе',
                'verbose_name_plural': 'Направления в работе',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('territory', models.CharField(choices=[('energy', 'Территория Энергии'), ('lampovo', 'Территория Ламповости'), ('hedonism', 'Территория Гедонизма'), ('meaning', 'Территория Смысла'), ('family', 'Родственная территория')], max_length=20, verbose_name='Территория')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Ник')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Есть премиум')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('evening_movie', 'Если бы твой вечер был фильмом'), ('money_habits', 'Про тебя сейчас скорее так'), ('share_skill_card', 'Карта, которой ты готов поделиться'), ('communication_style', 'Стиль общения'), ('company_role', 'Роль в компании'), ('why_fun_to_be_with', 'Со мной классно, потому что'), ('interesting_to_talk_with', 'Interesting To Talk With'), ('why_here', 'Здесь ради')], max_length=50, unique=True, verbose_name='Ключ')),
                ('text', models.TextField(verbose_name='Текст')),
                ('bot_response', models.TextField(blank=True, verbose_name='Ответ бота')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Номер')),
                ('type', models.CharField(choices=[('select', 'Выбор одного варианта'), ('multi_select', 'Выбор нескольких вариантов'), ('yes_no', 'Да/Нет')], default='multi_select', max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='core.user', verbose_name='Пользователь')),
                ('name', models.CharField(max_length=128, verbose_name='Как обращаться')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=20, verbose_name='Пол')),
                ('search_type', models.CharField(choices=[('city', 'В моем городе'), ('department', 'В моем департаменте'), ('gender', 'Среди своего пола'), ('interests', 'По схожим интересам')], max_length=20, verbose_name='Кого ищет')),
                ('workday_type', models.CharField(choices=[('office', 'В офисе (люблю деловой ритм и личные встречи)'), ('branch', 'В отделении (я там, где наши клиенты)'), ('remote', 'На удаленке (люблю работать из дома)'), ('hybrid', 'Гибрид (я и там, и там)')], max_length=20, verbose_name='Тип рабочего дня')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('career_focus_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.careerfocusdirection', verbose_name='Направление')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.city', verbose_name='Город')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_thread_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID темы в чате с ботом')),
                ('recipient_thread_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID темы в чате с ботом')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Завершен')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_matches', to='core.user', verbose_name='Пользователь 1')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to='core.user', verbose_name='Пользователь 2')),
            ],
            options={
                'verbose_name': 'Мэтч',
                'verbose_name_plural': 'Мэтчи',
            },
        ),
        migrations.CreateModel(
            name='ContactsExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принят'), ('declined', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_exchange_requests', to='core.match')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_exchange_requests', to='core.user')),
            ],
            options={
                'verbose_name': 'Обмен контактами',
                'verbose_name_plural': 'Обмены контактами',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Ответ')),
                ('bot_response', models.TextField(blank=True, verbose_name='Ответ бота')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='ProfileLifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle', models.CharField(choices=[('talk', 'Мне важно выговориться'), ('distract', 'Мне важно отвлечься от своих мыслей, разделив переживания другого'), ('physical', 'Мне важно физически переключиться')], max_length=20, verbose_name='Способ пережить сложный день')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyles', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Способ пережить сложный день',
                'verbose_name_plural': 'Способы пережить сложный день',
            },
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.interest', verbose_name='Интерес')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Выбранный интерес',
                'verbose_name_plural': 'Выбранные интересы',
            },
        ),
        migrations.CreateModel(
            name='ProfileAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.answer', verbose_name='Ответ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос анкеты',
                'verbose_name_plural': 'Ответы на вопрос анкеты',
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('initiator', models.F('recipient')), _negated=True), name='no_self_match'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('initiator', 'recipient')},
        ),
        migrations.AlterUniqueTogether(
            name='profilelifestyle',
            unique_together={('profile', 'lifestyle')},
        ),
        migrations.AlterUniqueTogether(
            name='profileinterest',
            unique_together={('profile', 'interest')},
        ),
        migrations.AlterUniqueTogether(
            name='profileanswer',
            unique_together={('profile', 'answer')},
        ),
    ]
