# Generated by Django 6.0.2 on 2026-02-13 07:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_questions_and_answers(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Question = apps.get_model('core', 'Question')
    Answer = apps.get_model('core', 'Answer')

    q1 = Question.objects.create(
        key='evening_movie',
        text='Если бы твой вечер был фильмом, это было бы:',
        bot_response='Выбери фильм, который лучше всего описывает твой вечер.'
    )
    Answer.objects.bulk_create([
        Answer(
            question=q1,
            text='Ирония судьбы, или С легким паром!',
            bot_response='Романтичный сценарий. Похоже, ты веришь в совпадения. Это хороший знак для мэтча.'
        ),
        Answer(
            question=q1,
            text='Операция Ы и другие приключения Шурика',
            bot_response='Люблю людей, у которых вечер — это квест. С тобой точно не скучно.'
        ),
        Answer(
            question=q1,
            text='Москва слезам не верит',
            bot_response='Амбициозный герой собственной истории. Уважительно.'
        ),
        Answer(
            question=q1,
            text='Собачье сердце',
            bot_response='Аналитик с кулинарным уклоном. Рациональность — сильная сторона.'
        ),
        Answer(
            question=q1,
            text='Иван Васильевич меняет профессию',
            bot_response='Гибкость уровня «адаптируюсь к любой эпохе». Это редкость.'
        ),
    ])


    q2 = Question.objects.create(
        key='money_habits',
        text='Про тебя сейчас скорее так:',
        bot_response='Интересный выбор! У каждого из нас свой уникальный взгляд на управление ресурсами и планирование. Именно такие различия в подходах делают общение в команде по-настоящему ценным и глубоким.'
    )
    Answer.objects.bulk_create([
        Answer(question=q2, text='Люблю, когда выгода чувствуется сразу — как кэшбек с каждой покупки'),
        Answer(question=q2, text='Хочу, чтобы деньги тихо росли каждый день — даже если я о них не думаю'),
        Answer(question=q2, text='Предпочитаю зафиксировать результат и не дергаться — пусть копится под хороший процент'),
        Answer(question=q2, text='Умею сочетать: и тратить с умом, и откладывать стратегически'),
    ])

    q3 = Question.objects.create(
        key='share_skill_card',
        text='Выбери карту, которой ты готов(а) поделиться:',
        bot_response='Бот дает оценку навыкам и интересам.'
    )
    Answer.objects.bulk_create([
        Answer(question=q3, text='Знаю, где в офисе/районе лучший кофе и тихое место', bot_response='О, локальный проводник. С такими дружат надолго.'),
        Answer(question=q3, text='Могу мотивировать на бег/спорт', bot_response='С тобой не получится отложить дела «до понедельника».'),
        Answer(question=q3, text='Посоветую сериал/фильм, который тебя затянет', bot_response='Опасно. После твоих советов люди пропадают на выходные.'),
        Answer(question=q3, text='Могу объяснить сложную штуку простыми словами', bot_response='Прекрасно. Я бы сам с тобой подружился!'),
        Answer(question=q3, text='Подскажу идею для короткой поездки или перезагрузки', bot_response='С тобой жизнь заиграет новыми красками ;)'),
        Answer(question=q3, text='Научу финансовой грамотности', bot_response='О, это серьезно! С тобой друзья точно не останутся с пустым кошельком в конце месяца!'),
    ])

    q4 = Question.objects.create(
        key='communication_style',
        text='Ты больше:',
        bot_response='Принял, я предупрежу твоего мэтча!'
    )
    Answer.objects.bulk_create([
        Answer(question=q4, text='Текстовый философ (люблю подумать и написать)'),
        Answer(question=q4, text='Голосовой импровизатор (быстро и по делу)'),
        Answer(question=q4, text='Коротко и ясно (ок, спс, погнали)'),
    ])

    q5 = Question.objects.create(
        key='company_role',
        text='В компании тебе чаще ближе роль:',
        bot_response='Бот оценивает стиль взаимодействия в команде.'
    )
    Answer.objects.bulk_create([
        Answer(question=q5, text='Инициатор — люблю предлагать и начинать', bot_response='Ты запускаешь процессы. Нужен тот, кто подхватит.'),
        Answer(question=q5, text='Командный игрок — люблю подключаться к движу', bot_response='Ты усиливаешь идеи. Это очень ценно.'),
        Answer(question=q5, text='Наблюдатель — люблю сначала посмотреть', bot_response='Ты видишь глубже, чем кажется. Интересный тип собеседника.'),
    ])

    q6 = Question.objects.create(
        key='why_fun_to_be_with',
        text='Со мной классно, потому что я…',
        bot_response='Бот оценивает сильные стороны личности.'
    )
    Answer.objects.bulk_create([
        Answer(question=q6, text='… умею поддержать', bot_response='Ты безопасное пространство. Это редкость.'),
        Answer(question=q6, text='… могу зарядить энергией', bot_response='С тобой уровень батарейки растет.'),
        Answer(question=q6, text='… умею объяснять сложное', bot_response='Ты переводчик с «заумного» на «человеческий».'),
        Answer(question=q6, text='… всегда за движ и новые идеи', bot_response='Спокойных мэтчей тебе не подберу ;)'),
        Answer(question=q6, text='… умею создавать уют и атмосферу', bot_response='С тобой разговоры не заканчиваются резко.'),
    ])

    q7 = Question.objects.create(
        key='interesting_to_talk_with',
        text='С кем тебе сейчас особенно интересно общаться?',
        bot_response='Бот оценивает предпочтения в общении.'
    )
    Answer.objects.bulk_create([
        Answer(question=q7, text='С теми, кто помогает расти и развиваться', bot_response='Ты в режиме апгрейда.'),
        Answer(question=q7, text='С теми, кто вдохновляет и двигает', bot_response='Тебе нужен вдохновитель рядом.'),
        Answer(question=q7, text='С теми, с кем можно поговорить по душам', bot_response='Понял, будут глубокие разговоры, нужно запастись вкусняшками'),
        Answer(question=q7, text='С теми, с кем можно просто посмеяться', bot_response='Иногда лучший мэтч — это лёгкость.'),
    ])

    q8 = Question.objects.create(
        key='why_here',
        text='Если честно, ты здесь больше ради:',
        bot_response='Бот оценивает мотивацию пользователя.'
    )
    Answer.objects.bulk_create([
        Answer(question=q8, text='Регулярного спорта с кем-то', bot_response='Подберу того, кто не отменит тренировку.'),
        Answer(question=q8, text='Новых друзей в компании', bot_response='Значит, важна лёгкость и регулярность общения.'),
        Answer(question=q8, text='Совместных идей и проектов', bot_response='Будет интеллектуальный тандем.'),
        Answer(question=q8, text='Просто живого человеческого общения', bot_response='Без формальностей. По-настоящему.'),
        Answer(question=q8, text='Чтобы научиться чему-то новому', bot_response='Люблю запрос на рост. Это всегда интересно.'),
    ])


def create_default_objects(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    City = apps.get_model('core', 'City')
    Department = apps.get_model('core', 'Department')
    Interest = apps.get_model('core', 'Interest')
    CareerFocusDirection = apps.get_model('core', 'CareerFocusDirection')

    cities = [
        'Москва',
        'Тверь',
        'Омск',
    ]
    for name in cities:
        City.objects.get_or_create(name=name)

    departments = [
        'Дивизион финансов',
        'Дивизион по управлению рисками',
        'Дирекция по персоналу и организационному развитию',
        'Дирекция юридического сопровождения',
        'Дирекция контроля и безопасности',
        'Дивизион информационных технологий',
        'Дивизион взыскания и операционного управления',
        'Дивизион розничного бизнеса',
        'Дивизион корпоративного бизнеса и глобальных рынков',
        'Дирекция по стратегии и инновациям',
        'Дирекция маркетинга и связей с общественностью',
        'Дирекция по повышению эффективности процессов и внедрению искусственного интеллекта',
        'Служба внутреннего аудита',
    ]
    for name in departments:
        Department.objects.get_or_create(name=name)

    interests_data = {
        'energy': [
            'Играть в команде (футбол, волейбол)',
            'Заниматься единоборствами (бокс)',
            'Играть с ракеткой (теннис, настольный теннис, падел)',
            'Плавать или кататься на SUP-борде',
            'Крутить педали (велосипед, сайклинг)',
            'Бегать на короткие или длинные дистанции',
            'Вести активный и здоровый образ жизни (ЗОЖ)',
            'Свой вариант',
        ],
        'lampovo': [
            'Читать и обсуждать книги',
            'Заниматься творчеством и искусством',
            'Смотреть и разбирать кино',
            'Создавать вещи своими руками (вязание, рукоделие)',
            'Ухаживать за растениями и изучать природу',
            'Свой вариант',
        ],
        'hedonism': [
            'Готовить и пробовать еду',
            'Путешествовать и открывать новые страны',
            'Ходить на рыбалку и проводить время у воды',
            'Расслабляться в бане и посещать спа',
            'Наслаждаться эстетикой момента и качественным отдыхом',
            'Свой вариант',
        ],
        'meaning': [
            'Практиковать иностранные языки и общаться',
            'Играть в видеоигры или настолки',
            'Побеждать в интеллектуальных квизах и битвах умов',
            'Слушать музыку и разбираться в ней',
            'Коллекционировать пластинки',
            'Погружаться в культуру аниме',
            'Играть на музыкальном инструменте',
            'Свой вариант',
        ],
        'family': [
            'Заниматься семейным уютом и воспитанием детей',
            'Заботиться о домашних питомцах',
            'Находить крутые вещи или избавляться от лишнего',
            'Разбираться в автомобилях',
        ],
    }
    for territory, names in interests_data.items():
        for name in names:
            Interest.objects.get_or_create(
                name=name,
                defaults={'territory': territory},
            )

    career_focus_data = {
        'result': [
            'Целеустремленность (вижу цель — иду к ней)',
            'Ответственность (держу слово и отвечаю за итог)',
        ],
        'development': [
            'Инициативность (предлагаю идеи и пробую новое)',
            'Гибкость (быстро адаптируюсь к любым изменениям)',
        ],
        'enjoyment': [
            'Партнерство (командная работа и поддержка)',
            'Позитив и энергия (заряжаю коллег и кайфую от процесса)',
        ],
    }
    for focus, names in career_focus_data.items():
        for name in names:
            CareerFocusDirection.objects.get_or_create(
                name=name,
                defaults={'career_focus': focus},
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFocusDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('career_focus', models.CharField(choices=[('result', 'Результат'), ('development', 'Развитие'), ('enjoyment', 'Удовольствие')], max_length=20, verbose_name='Базовое направление')),
            ],
            options={
                'verbose_name': 'Направление в работе',
                'verbose_name_plural': 'Направления в работе',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('territory', models.CharField(choices=[('energy', 'Территория Энергии'), ('lampovo', 'Территория Ламповости'), ('hedonism', 'Территория Гедонизма'), ('meaning', 'Территория Смысла'), ('family', 'Родственная территория')], max_length=20, verbose_name='Территория')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Ник')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Есть премиум')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('evening_movie', 'Если бы твой вечер был фильмом'), ('money_habits', 'Про тебя сейчас скорее так'), ('share_skill_card', 'Карта, которой ты готов поделиться'), ('communication_style', 'Стиль общения'), ('company_role', 'Роль в компании'), ('why_fun_to_be_with', 'Со мной классно, потому что'), ('why_here', 'Здесь ради')], max_length=50, unique=True, verbose_name='Ключ')),
                ('text', models.TextField(verbose_name='Текст')),
                ('bot_response', models.TextField(blank=True, verbose_name='Ответ бота')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='core.user', verbose_name='Пользователь')),
                ('name', models.CharField(max_length=128, verbose_name='Как обращаться')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=20, verbose_name='Пол')),
                ('search_type', models.CharField(choices=[('city', 'В моем городе'), ('department', 'В моем департаменте'), ('gender', 'Среди своего пола'), ('interests', 'По схожим интересам')], max_length=20, verbose_name='Кого ищет')),
                ('match_type', models.CharField(choices=[('my_city', 'Мой город'), ('other_city', 'Другой регион')], max_length=20, verbose_name='Идеальный мэтч')),
                ('workday_type', models.CharField(choices=[('office', 'В офисе (люблю деловой ритм и личные встречи)'), ('branch', 'В отделении (я там, где наши клиенты)'), ('remote', 'На удаленке (люблю работать из дома)')], max_length=20, verbose_name='Тип рабочего дня')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('career_focus_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.careerfocusdirection', verbose_name='Направление')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.city', verbose_name='Город')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.department', verbose_name='Департамент')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.interest', verbose_name='Интерес')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_thread_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID темы в чате с ботом')),
                ('recipient_thread_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID темы в чате с ботом')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Завершен')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_matches', to='core.user', verbose_name='Пользователь 1')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to='core.user', verbose_name='Пользователь 2')),
            ],
            options={
                'verbose_name': 'Мэтч',
                'verbose_name_plural': 'Мэтчи',
            },
        ),
        migrations.CreateModel(
            name='ContactsExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принят'), ('declined', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_exchange_requests', to='core.match')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_exchange_requests', to='core.user')),
            ],
            options={
                'verbose_name': 'Обмен контактами',
                'verbose_name_plural': 'Обмены контактами',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Ответ')),
                ('bot_response', models.TextField(blank=True, verbose_name='Ответ бота')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='ProfileLifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle', models.CharField(choices=[('talk', 'Мне важно выговориться'), ('distract', 'Мне важно отвлечься от своих мыслей, разделив переживания другого'), ('physical', 'Мне важно физически переключиться')], max_length=20, verbose_name='Способ пережить сложный день')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyles', to='core.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.answer', verbose_name='Ответ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('initiator', models.F('recipient')), _negated=True), name='no_self_match'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('initiator', 'recipient')},
        ),
        migrations.AlterUniqueTogether(
            name='profilelifestyle',
            unique_together={('profile', 'lifestyle')},
        ),
        migrations.AlterUniqueTogether(
            name='profileanswer',
            unique_together={('profile', 'answer')},
        ),
        migrations.RunPython(create_questions_and_answers, migrations.RunPython.noop),
        migrations.RunPython(create_default_objects, migrations.RunPython.noop),
    ]
