# Generated by Django 6.0.2 on 2026-02-13 14:57
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_questions_and_answers(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Question = apps.get_model('core', 'Question')
    Answer = apps.get_model('core', 'Answer')

    q1 = Question.objects.create(
        key='evening_movie',
        text='Представь что твой вечер – это фильм…',
    )
    Answer.objects.bulk_create([
        Answer(
            question=q1,
            text='«Ирония судьбы, или С легким паром!»: '
                 'Вечером ты начинаешь ощущать себя Женей Лукашиным, '
                 'мечтая случайно попасть в другой город и встретить свою судьбу.',
            bot_response='Романтичный сценарий. Похоже, ты веришь в совпадения. '
                         'Это хороший знак для мэтча.'
        ),
        Answer(
            question=q1,
            text='«Форест Гамп»: Движение — это жизнь. '
                 'Ты не ищешь повода присесть и остаешься на ногах '
                 'даже тогда, когда другие уже выбились из сил.',
            bot_response='Люблю людей, у которых вечер — это квест. '
                         'С тобой точно не скучно.'
        ),
        Answer(
            question=q1,
            text='«Великий Гэтсби»: Ты — душа компании. '
                 'Твой вечер — это блеск, общение и атмосфера вечного праздника, '
                 'где ты всегда в центре внимания.',
            bot_response='Амбициозный герой собственной истории. Уважительно.'
        ),
        Answer(
            question=q1,
            text='«Титаник»: Настоящий капитан. '
                 'Ты берешь на себя ответственность и сохраняешь верность своему делу '
                 'до самого конца, что бы ни происходило вокруг.',
            bot_response='Аналитик с кулинарным уклоном. '
                         'Рациональность — сильная сторона.'
        ),
        Answer(
            question=q1,
            text='«Шерлок Холмс»: Время интеллектуального уединения. '
                 'Ты отключаешься от шума, чтобы проанализировать задачи '
                 'и выстроить логические цепочки.',
            bot_response='Гибкость уровня «адаптируюсь к любой эпохе». '
                         'Это редкость.'
        ),
    ])

    q2 = Question.objects.create(
        key='money_habits',
        text='Про тебя сейчас скорее так:',
        bot_response='Интересный выбор! У каждого из нас свой уникальный взгляд на управление ресурсами и планирование. Именно такие различия в подходах делают общение в команде по-настоящему ценным и глубоким.'
    )
    Answer.objects.bulk_create([
        Answer(question=q2, text='Люблю, когда выгода чувствуется сразу — как кэшбек с каждой покупки'),
        Answer(question=q2, text='Хочу, чтобы деньги тихо росли каждый день — даже если я о них не думаю'),
        Answer(question=q2, text='Предпочитаю зафиксировать результат и не дергаться — пусть копится под хороший процент'),
        Answer(question=q2, text='Умею сочетать: и тратить с умом, и откладывать стратегически'),
    ])

    q3 = Question.objects.create(
        key='share_skill_card',
        text='Выбери карту, которой ты готов(а) поделиться:',
        bot_response='Бот дает оценку навыкам и интересам.'
    )
    Answer.objects.bulk_create([
        Answer(question=q3, text='Знаю, где в офисе/районе лучший кофе и тихое место', bot_response='О, локальный проводник. С такими дружат надолго.'),
        Answer(question=q3, text='Могу мотивировать на бег/спорт', bot_response='С тобой не получится отложить дела «до понедельника».'),
        Answer(question=q3, text='Посоветую сериал/фильм, который тебя затянет', bot_response='Опасно. После твоих советов люди пропадают на выходные.'),
        Answer(question=q3, text='Могу объяснить сложную штуку простыми словами', bot_response='Прекрасно. Я бы сам с тобой подружился!'),
        Answer(question=q3, text='Подскажу идею для короткой поездки или перезагрузки', bot_response='С тобой жизнь заиграет новыми красками ;)'),
        Answer(question=q3, text='Могу научить финансовой грамотности', bot_response='О, это серьезно! С тобой друзья точно не останутся с пустым кошельком в конце месяца!'),
    ])

    q4 = Question.objects.create(
        key='communication_style',
        text='Ты больше:',
        bot_response='Принял, я предупрежу твоего мэтча!'
    )
    Answer.objects.bulk_create([
        Answer(question=q4, text='Текстовый философ (подумать и написать)'),
        Answer(question=q4, text='Голосовой импровизатор (быстро и по делу)'),
        Answer(question=q4, text='Коротко и ясно (ок, спс, погнали)'),
    ])

    q5 = Question.objects.create(
        key='company_role',
        text='В компании тебе чаще ближе роль:',
        bot_response='Бот оценивает стиль взаимодействия в команде.'
    )
    Answer.objects.bulk_create([
        Answer(question=q5, text='Инициатор — люблю предлагать и начинать', bot_response='Ты запускаешь процессы. Нужен тот, кто подхватит.'),
        Answer(question=q5, text='Командный игрок — люблю подключаться к движу', bot_response='Ты усиливаешь идеи. Это очень ценно.'),
        Answer(question=q5, text='Наблюдатель — люблю сначала посмотреть', bot_response='Ты видишь глубже, чем кажется. Интересный тип собеседника.'),
    ])

    q6 = Question.objects.create(
        key='why_fun_to_be_with',
        text='Со мной классно, потому что я…',
        bot_response='Бот оценивает сильные стороны личности.'
    )
    Answer.objects.bulk_create([
        Answer(question=q6, text='Умею поддержать и выслушать', bot_response='Ты безопасное пространство. Это редкость.'),
        Answer(question=q6, text='Могу зарядить энергией', bot_response='С тобой уровень батарейки растет.'),
        Answer(question=q6, text='Умею объяснять сложное', bot_response='Ты переводчик с «заумного» на «человеческий».'),
        Answer(question=q6, text='Всегда за движ и новые идеи', bot_response='Спокойных мэтчей тебе не подберу ;)'),
        Answer(question=q6, text='Умею создавать уют и атмосферу', bot_response='С тобой разговоры не заканчиваются резко.'),
    ])

    q7 = Question.objects.create(
        key='interesting_to_talk_with',
        text='С кем тебе сейчас особенно интересно общаться?',
        bot_response='Бот оценивает предпочтения в общении.'
    )
    Answer.objects.bulk_create([
        Answer(question=q7, text='С теми, кто помогает расти и развиваться', bot_response='Ты в режиме апгрейда.'),
        Answer(question=q7, text='С теми, кто вдохновляет и двигает', bot_response='Тебе нужен вдохновитель рядом.'),
        Answer(question=q7, text='С теми, с кем можно поговорить по душам', bot_response='Понял, будут глубокие разговоры, нужно запастись вкусняшками'),
        Answer(question=q7, text='С теми, с кем можно просто посмеяться', bot_response='Иногда лучший мэтч — это лёгкость.'),
    ])

    q8 = Question.objects.create(
        key='why_here',
        text='Если честно, ты здесь больше ради:',
        bot_response='Бот оценивает мотивацию пользователя.'
    )
    Answer.objects.bulk_create([
        Answer(question=q8, text='Регулярного спорта с кем-то', bot_response='Подберу того, кто не отменит тренировку.'),
        Answer(question=q8, text='Новых друзей в компании', bot_response='Значит, важна лёгкость и регулярность общения.'),
        Answer(question=q8, text='Совместных идей и проектов', bot_response='Будет интеллектуальный тандем.'),
        Answer(question=q8, text='Просто живого человеческого общения', bot_response='Без формальностей. По-настоящему.'),
        Answer(question=q8, text='Чтобы научиться чему-то новому', bot_response='Люблю запрос на рост. Это всегда интересно.'),
    ])


def create_default_objects(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    City = apps.get_model('core', 'City')
    Department = apps.get_model('core', 'Department')
    Interest = apps.get_model('core', 'Interest')
    CareerFocusDirection = apps.get_model('core', 'CareerFocusDirection')

    cities = [
        'Москва',
        'Тверь',
        'Омск',
    ]
    for name in cities:
        City.objects.get_or_create(name=name)

    departments = [
        'Дивизион финансов',
        'Дивизион по управлению рисками',
        'Дирекция по персоналу и организационному развитию',
        'Дирекция юридического сопровождения',
        'Дирекция контроля и безопасности',
        'Дивизион информационных технологий',
        'Дивизион взыскания и операционного управления',
        'Дивизион розничного бизнеса',
        'Дивизион корпоративного бизнеса и глобальных рынков',
        'Дирекция по стратегии и инновациям',
        'Дирекция маркетинга и связей с общественностью',
        'Дирекция по повышению эффективности процессов и внедрению искусственного интеллекта',
        'Служба внутреннего аудита',
    ]
    for name in departments:
        Department.objects.get_or_create(name=name)

    interests_data = {
        'energy': [
            'Командный спорт (футбол, волейбол)',
            'Единоборства',
            'Теннис',
            'Вейкбординг, сап',
            'Велосипед, сайклинг',
            'Бег',
            'ЗОЖ',
        ],
        'lampovo': [
            'Читать и обсуждать книги',
            'Ходить в галереи, смотреть искусство',
            'Слушать и коллекционировать музыку',
            'Играть на музыкальных инструментах',
            'Смотреть и разбирать кино',
            'Создавать вещи своими руками',
            'Выращивать растения',
        ],
        'hedonism': [
            'Путешествовать',
            'Пробовать интересную еду',
            'Ходить на рыбалку',
            'Ходить в баню или СПА',
            'Проводить время на природе',
            'Отдых в формате all inclusive',
        ],
        'meaning': [
            'Практиковать иностранные языки',
            'Играть в видеоигры',
            'Играть в настольные игры',
            'Побеждать в интеллектуальных квизах',
            'Погружаться в культуру аниме',
        ],
        'family': [
            'Создавать семейный уют',
            'Заниматься воспитанием детей',
            'Заботиться о домашних питомцах',
            'Находить крутые вещи',
            'Наводить порядок',
            'Разбираться в автомобилях',
        ],
    }
    for territory, names in interests_data.items():
        for name in names:
            Interest.objects.get_or_create(
                name=name,
                defaults={'territory': territory},
            )

    career_focus_data = {
        'result': [
            'Целеустремленность (вижу цель — иду к ней)',
            'Ответственность за результат',
        ],
        'development': [
            'Инициативность и поток идей',
            'Гибкость и готовность к изменениям',
        ],
        'enjoyment': [
            'Командная работа и поддержка',
            'Заряжаю и кайфую от процесса',
        ],
    }
    for focus, names in career_focus_data.items():
        for name in names:
            CareerFocusDirection.objects.get_or_create(
                name=name,
                defaults={'career_focus': focus},
            )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_questions_and_answers, migrations.RunPython.noop),
        migrations.RunPython(create_default_objects, migrations.RunPython.noop),
    ]
